name: Build firmware

on: 
  workflow_dispatch:
    inputs:
      board:
        type: choice
        description: Choose board
        options:
        - esp32
        - esp32-s3
        - esp32-s3-mini
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e ${{ github.event.inputs.board }}

      - name: Save firmware file
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/${{ github.event.inputs.board }}/firmware.elf
          
